# ArborVia Layout Module
# Layout algorithms and results

set(ARBORVIA_LAYOUT_SOURCES
    src/layout/LayoutResult.cpp
    src/layout/SugiyamaLayout.cpp
    src/layout/ManualLayoutManager.cpp
    src/layout/LayoutUtils.cpp
    src/layout/LayoutSerializer.cpp
    src/layout/OrthogonalRouter.cpp
    src/layout/ConstraintManager.cpp
    src/layout/ConstraintConfig.cpp
    src/layout/constraints/MinDistanceConstraint.cpp
    src/layout/sugiyama/CycleRemoval.cpp
    src/layout/sugiyama/LayerAssignment.cpp
    src/layout/sugiyama/CrossingMinimization.cpp
    src/layout/sugiyama/CoordinateAssignment.cpp
    src/layout/sugiyama/EdgeRouting.cpp
    src/layout/sugiyama/GridSnapCalculator.cpp
    src/layout/sugiyama/ChannelRouter.cpp
    src/layout/sugiyama/AStarRetrySystem.cpp
    src/layout/sugiyama/EdgeValidator.cpp
    src/layout/sugiyama/SnapIndexManager.cpp
    src/layout/sugiyama/ObstacleMap.cpp
    src/layout/sugiyama/AStarPathFinder.cpp
    src/layout/sugiyama/LShapedPathFinder.cpp
    src/layout/sugiyama/PathIntersection.cpp
    src/layout/sugiyama/SelfLoopRouter.cpp
    src/layout/sugiyama/PathCleanup.cpp
    src/layout/sugiyama/AStarEdgeOptimizer.cpp
    src/layout/sugiyama/GeometricEdgeOptimizer.cpp
    src/layout/sugiyama/AStarOptimizerFactory.cpp
    src/layout/sugiyama/GeometricOptimizerFactory.cpp
    src/layout/PathRoutingCoordinator.cpp
    src/layout/ValidRegionCalculator.cpp
    src/layout/EdgePenaltySystem.cpp
    src/layout/OptimizerConfig.cpp
    src/layout/OptimizerRegistry.cpp
    src/layout/BuiltinPenalties.cpp
    src/layout/EdgeNudger.cpp
)

set(ARBORVIA_LAYOUT_HEADERS
    include/arborvia/layout/LayoutOptions.h
    include/arborvia/layout/LayoutResult.h
    include/arborvia/layout/LayoutTypes.h
    include/arborvia/layout/LayoutEnums.h
    include/arborvia/layout/ManualLayoutState.h
    include/arborvia/layout/ILayout.h
    include/arborvia/layout/SugiyamaLayout.h
    include/arborvia/layout/ManualLayout.h
    include/arborvia/layout/ManualLayoutManager.h
    include/arborvia/layout/LayoutUtils.h
    include/arborvia/layout/LayoutSerializer.h
    include/arborvia/layout/OrthogonalRouter.h
    include/arborvia/layout/IDragConstraint.h
    include/arborvia/layout/ConstraintManager.h
    include/arborvia/layout/ConstraintConfig.h
    include/arborvia/layout/MinDistanceConstraint.h
    include/arborvia/layout/IEdgeOptimizer.h
    include/arborvia/layout/ValidRegionCalculator.h
    include/arborvia/layout/IEdgePenalty.h
    include/arborvia/layout/EdgePenaltySystem.h
    include/arborvia/layout/OptimizerConfig.h
    include/arborvia/layout/IEdgeOptimizerFactory.h
    include/arborvia/layout/OptimizerRegistry.h
    include/arborvia/layout/BuiltinPenalties.h
    include/arborvia/layout/EdgeNudger.h
)
